### ISSUE TITLE
[Question] - Formatting the display does not remain after saving

### ISSUE THREAD

**Issue by andrew-mcnaught** [NovatecConsulting/novatec-service-dependency-graph-panel#88] opened 2021-06-09 17:42 UTC
Hey all,

I recently installed this plugin and was using this with a few basic examples. When in place I manually moved around a few of the nodes and then saved the dashboard. When I then refresh the dashboard the nodes are reset back to default. Is there something I am missing with this or is there a way to save this in a display you want manually?

Thanks,
Andrew

**Comment by MariusBrill** [comment] 2021-06-17 07:45
Hi @andrew-mcnaught 
As for now there is no such feature. 
There is however already a smiliar [feature-request ](https://github.com/NovatecConsulting/novatec-service-dependency-graph-panel/issues/48). 
Greetings
Marius

**Comment by MariusBrill** [comment] 2022-04-27 07:17
Duplicate of #48

**Closed by MariusBrill** 2022-04-27 07:17 UTC
Labels: question
