### ISSUE TITLE
Pin node locations in layout?

### ISSUE THREAD

**Issue by mckingula** [NovatecConsulting/novatec-service-dependency-graph-panel#103] opened 2022-03-13 10:14 UTC
Hi. The plug-in is really nice my only feedback is whether its possible to _pin_ the node locations on the panel so they are consistent each time it loads rather than the graph redrawing every time which I guess is a way to optimise the layout for a dynamic dataset. In my use case the nodes are known in advance so having them in the same place each time and laid out in a way that makes sense to me would be helpful. Thanks

**Comment by MariusBrill** [comment] 2022-03-22 08:24
HI @mckingula,

Thank you for your feedback! Others also had the[ same thought](https://github.com/NovatecConsulting/novatec-service-dependency-graph-panel/issues/48).
We will include the feature in our upcoming major release.

Best regards
Marius

**Comment by MariusBrill** [comment] 2022-04-27 07:07
Duplicate of #48

**Closed by MariusBrill** 2022-04-27 07:07 UTC
Labels: duplicate
